-- 创建 deposit_requests 表
-- 此表用于存储用户的充币申请

CREATE TABLE IF NOT EXISTS deposit_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL DEFAULT 'crypto' CHECK (type IN ('crypto', 'wire', 'bank')),
  currency VARCHAR(20) NOT NULL,
  amount NUMERIC(20, 8) NOT NULL,
  tx_hash TEXT,
  proof_image TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  remark TEXT,
  processed_by INTEGER REFERENCES users(id),
  processed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引以优化查询性能
CREATE INDEX IF NOT EXISTS idx_deposit_requests_user_id ON deposit_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_deposit_requests_status ON deposit_requests(status);
CREATE INDEX IF NOT EXISTS idx_deposit_requests_created_at ON deposit_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deposit_requests_currency ON deposit_requests(currency);

-- 创建触发器自动更新 updated_at 字段
CREATE OR REPLACE FUNCTION update_deposit_requests_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER deposit_requests_updated_at_trigger
BEFORE UPDATE ON deposit_requests
FOR EACH ROW
EXECUTE FUNCTION update_deposit_requests_updated_at();

-- 添加表注释
COMMENT ON TABLE deposit_requests IS '充值申请表，存储用户的各种充值申请记录';
COMMENT ON COLUMN deposit_requests.type IS '充值类型：crypto-加密货币，wire-电汇，bank-银行转账';
COMMENT ON COLUMN deposit_requests.amount IS '充值金额，支持小数点后8位';
COMMENT ON COLUMN deposit_requests.tx_hash IS '交易哈希/钱包地址';
COMMENT ON COLUMN deposit_requests.proof_image IS '支付凭证图片URL或Base64';
COMMENT ON COLUMN deposit_requests.status IS '状态：pending-待审核，approved-已通过，rejected-已拒绝';
