-- =====================================================
-- ST7 Trading Platform 数据库表创建脚本
-- 执行顺序：请按照文件中的顺序依次执行
-- =====================================================

-- =====================================================
-- 1. deposit_requests 表（充币申请表）
-- =====================================================
CREATE TABLE IF NOT EXISTS deposit_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'crypto' CHECK (type IN ('crypto', 'wire', 'bank')),
  currency VARCHAR(20) NOT NULL,
  amount NUMERIC(20, 8) NOT NULL,
  tx_hash TEXT,
  proof_image TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  remark TEXT,
  processed_by INTEGER,
  processed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_deposit_requests_user_id ON deposit_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_deposit_requests_status ON deposit_requests(status);
CREATE INDEX IF NOT EXISTS idx_deposit_requests_created_at ON deposit_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deposit_requests_currency ON deposit_requests(currency);

-- 创建触发器自动更新 updated_at 字段
CREATE OR REPLACE FUNCTION update_deposit_requests_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS deposit_requests_updated_at_trigger ON deposit_requests;
CREATE TRIGGER deposit_requests_updated_at_trigger
BEFORE UPDATE ON deposit_requests
FOR EACH ROW
EXECUTE FUNCTION update_deposit_requests_updated_at();

-- 添加表注释
COMMENT ON TABLE deposit_requests IS '充值申请表，存储用户的各种充值申请记录';
COMMENT ON COLUMN deposit_requests.type IS '充值类型：crypto-加密货币，wire-电汇，bank-银行转账';
COMMENT ON COLUMN deposit_requests.amount IS '充值金额，支持小数点后8位';
COMMENT ON COLUMN deposit_requests.tx_hash IS '交易哈希/钱包地址';
COMMENT ON COLUMN deposit_requests.proof_image IS '支付凭证图片URL或Base64';
COMMENT ON COLUMN deposit_requests.status IS '状态：pending-待审核，approved-已通过，rejected-已拒绝';


-- =====================================================
-- 2. users 表（用户表）
-- =====================================================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  account_type VARCHAR(20) NOT NULL DEFAULT 'demo' CHECK (account_type IN ('demo', 'real')),
  balance NUMERIC(20, 8) NOT NULL DEFAULT 0,
  credit_score INTEGER DEFAULT 0,
  is_verified BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_account_type ON users(account_type);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at DESC);

-- 创建触发器自动更新 updated_at 字段
CREATE OR REPLACE FUNCTION update_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_updated_at_trigger ON users;
CREATE TRIGGER users_updated_at_trigger
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_users_updated_at();

-- 添加表注释
COMMENT ON TABLE users IS '用户表，存储用户基本信息';
COMMENT ON COLUMN users.account_type IS '账户类型：demo-模拟账户，real-正式账户';
COMMENT ON COLUMN users.balance IS '账户余额';
COMMENT ON COLUMN users.credit_score IS '信用分';


-- =====================================================
-- 3. applications 表（申请表，用于实名认证等）
-- =====================================================
CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL CHECK (type IN ('deposit', 'withdraw', 'verification')),
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  amount NUMERIC(20, 8),
  bank_name VARCHAR(100),
  bank_account VARCHAR(200),
  real_name VARCHAR(100),
  id_card VARCHAR(50),
  id_card_front_url TEXT,
  id_card_back_url TEXT,
  reject_reason TEXT,
  reviewed_by VARCHAR(100),
  reviewed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_applications_user_id ON applications(user_id);
CREATE INDEX IF NOT EXISTS idx_applications_type ON applications(type);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_applications_created_at ON applications(created_at DESC);

-- 创建触发器自动更新 updated_at 字段
CREATE OR REPLACE FUNCTION update_applications_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS applications_updated_at_trigger ON applications;
CREATE TRIGGER applications_updated_at_trigger
BEFORE UPDATE ON applications
FOR EACH ROW
EXECUTE FUNCTION update_applications_updated_at();

-- 添加表注释
COMMENT ON TABLE applications IS '申请表，用于实名认证、入金、出金等申请';
COMMENT ON COLUMN applications.type IS '申请类型：deposit-入金，withdraw-出金，verification-实名认证';


-- =====================================================
-- 4. crypto_addresses 表（加密货币地址表）
-- =====================================================
CREATE TABLE IF NOT EXISTS crypto_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency VARCHAR(20) NOT NULL,
  protocol VARCHAR(20) NOT NULL, -- TRC20, ERC20, BEP20 等
  address TEXT NOT NULL,
  network VARCHAR(50),
  min_amount NUMERIC(20, 8) DEFAULT 0,
  max_amount NUMERIC(20, 8) DEFAULT 999999999,
  fee NUMERIC(20, 8) DEFAULT 0,
  fee_type VARCHAR(10) DEFAULT 'fixed' CHECK (fee_type IN ('fixed', 'percentage')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_crypto_addresses_currency ON crypto_addresses(currency);
CREATE INDEX IF NOT EXISTS idx_crypto_addresses_status ON crypto_addresses(status);

-- 创建触发器自动更新 updated_at 字段
CREATE OR REPLACE FUNCTION update_crypto_addresses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS crypto_addresses_updated_at_trigger ON crypto_addresses;
CREATE TRIGGER crypto_addresses_updated_at_trigger
BEFORE UPDATE ON crypto_addresses
FOR EACH ROW
EXECUTE FUNCTION update_crypto_addresses_updated_at();

-- 添加表注释
COMMENT ON TABLE crypto_addresses IS '加密货币收款地址表';


-- =====================================================
-- 5. market_adjustments 表（市场调控记录表）
-- =====================================================
CREATE TABLE IF NOT EXISTS market_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(50) NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  before_price NUMERIC(20, 8) NOT NULL,
  after_price NUMERIC(20, 8) NOT NULL,
  change_percent VARCHAR(20),
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_market_adjustments_symbol ON market_adjustments(symbol);
CREATE INDEX IF NOT EXISTS idx_market_adjustments_created_at ON market_adjustments(created_at DESC);

-- 添加表注释
COMMENT ON TABLE market_adjustments IS '市场调控记录表';


-- =====================================================
-- 6. credit_adjustments 表（信用调整记录表）
-- =====================================================
CREATE TABLE IF NOT EXISTS credit_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  before_score INTEGER NOT NULL,
  after_score INTEGER NOT NULL,
  change_value INTEGER NOT NULL,
  reason TEXT NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_credit_adjustments_user_id ON credit_adjustments(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_adjustments_created_at ON credit_adjustments(created_at DESC);

-- 添加表注释
COMMENT ON TABLE credit_adjustments IS '信用调整记录表';


-- =====================================================
-- 插入初始测试数据
-- =====================================================

-- 插入加密货币地址
INSERT INTO crypto_addresses (currency, protocol, address, network, min_amount, max_amount, status) VALUES
('BTC', 'BTC', 'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh', 'Bitcoin', 0.001, 10, 'active'),
('ETH', 'ERC20', '0x71C7656EC7ab88b098defB751B7401B5f6d8976F', 'Ethereum', 0.01, 100, 'active'),
('USDT', 'TRC20', 'T9zXqYvW5uT4sR3qP2oN1mK0jL9kI8jH7gF6e', 'Tron', 10, 9999999, 'active'),
('USDT', 'ERC20', '0xdAC17F958D2ee523a2206206994597C13D831ec7', 'Ethereum', 10, 9999999, 'active')
ON CONFLICT DO NOTHING;

-- =====================================================
-- 执行完成提示
-- =====================================================

-- 检查表是否创建成功
SELECT 
  '✅ deposit_requests' as table_name,
  (SELECT COUNT(*) FROM deposit_requests) as row_count
UNION ALL
SELECT 
  '✅ users',
  (SELECT COUNT(*) FROM users)
UNION ALL
SELECT 
  '✅ applications',
  (SELECT COUNT(*) FROM applications)
UNION ALL
SELECT 
  '✅ crypto_addresses',
  (SELECT COUNT(*) FROM crypto_addresses)
UNION ALL
SELECT 
  '✅ market_adjustments',
  (SELECT COUNT(*) FROM market_adjustments)
UNION ALL
SELECT 
  '✅ credit_adjustments',
  (SELECT COUNT(*) FROM credit_adjustments);
